#!/usr/bin/env python
"""Evaluate generated BrainFLORA captions across modalities and subjects."""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
CAPTION_ROOT = REPO_ROOT / "Caption"
EVAL_SCRIPT = CAPTION_ROOT / "BrainHub" / "eval_caption.py"

MODALITY_DIR = {
    "eeg": "EEG_caption",
    "meg": "MEG_caption",
    "fmri": "fMRI_caption",
}

MODALITY_FILE_TAG = {
    "eeg": "eeg",
    "meg": "meg",
    "fmri": "fMRI",
}

DEFAULT_REFERENCES = {
    "eeg": CAPTION_ROOT / "EEG_caption" / "caption_EEG_GT.json",
    "meg": CAPTION_ROOT / "EEG_caption" / "caption_EEG_GT.json",
    "fmri": CAPTION_ROOT / "fMRI_caption" / "caption_fMRI_GT.json",
}

DEFAULT_IMAGE_DIRS = {
    "eeg": Path("/vePFS-0x0d/visual/dataset/THINGS_EEG/images_set/test_images"),
    "meg": Path("/vePFS-0x0d/visual/dataset/THINGS_EEG/images_set/test_images"),
    "fmri": Path("/vePFS-0x0d/visual/dataset/fmri_dataset/images/test_images"),
}

METRICS = [
    "BLEU-1",
    "BLEU-2",
    "BLEU-3",
    "BLEU-4",
    "METEOR",
    "ROUGE",
    "CIDER",
    "SPICE",
    "CLIPScore",
    "RefCLIPScore",
]

METRIC_PATTERN = re.compile(r"^(BLEU-\d|METEOR|ROUGE|CIDER|SPICE|CLIPScore|RefCLIPScore):\s*([-+0-9.eE]+)\s*$")
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".tiff"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate BrainFLORA caption JSON files generated by Shikra "
            "with BrainHub metrics."
        )
    )
    parser.add_argument("--modalities", nargs="+", default=["eeg", "meg", "fmri"], choices=sorted(MODALITY_DIR))
    parser.add_argument("--conditions", nargs="+", default=["Prior", "woPrior"], choices=["Prior", "woPrior"])
    parser.add_argument("--subjects", nargs="+", default=[f"{i:02d}" for i in range(1, 11)])
    parser.add_argument("--caption-root", type=Path, default=CAPTION_ROOT)
    parser.add_argument("--eval-script", type=Path, default=EVAL_SCRIPT)
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT / "outputs" / "caption_metrics")
    parser.add_argument("--candidate-pattern", default="shikra_{tag}_sub_{subject}_caption.json")
    parser.add_argument(
        "--references-json",
        type=Path,
        default=None,
        help="Use one reference JSON for all modalities. Defaults are modality-specific.",
    )
    parser.add_argument(
        "--image-dir",
        type=Path,
        default=None,
        help="Use one image directory for all modalities. Defaults are modality-specific.",
    )
    parser.add_argument("--skip-missing", action="store_true", help="Skip missing candidate files instead of failing.")
    parser.add_argument("--dry-run", action="store_true", help="Validate inputs and print planned evaluations only.")
    return parser.parse_args()


def normalize_subject(subject: str) -> str:
    subject = subject.strip()
    if subject.startswith("sub-"):
        subject = subject.split("-", 1)[1]
    return f"{int(subject):02d}"


def load_json(path: Path) -> Mapping[str, object]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object keyed by image id.")
    return data


def collect_images(image_dir: Path) -> Dict[str, Path]:
    if not image_dir.exists():
        raise FileNotFoundError(f"Image directory does not exist: {image_dir}")
    images: Dict[str, Path] = {}
    for root, _, files in os.walk(image_dir):
        for filename in files:
            path = Path(root) / filename
            if path.suffix.lower() in IMAGE_EXTS:
                images[path.stem] = path
    if not images:
        raise FileNotFoundError(f"No supported images found under {image_dir}")
    return images


def make_eval_image_dir(images: Mapping[str, Path], image_ids: Sequence[str], temp_root: Path) -> Path:
    eval_dir = temp_root / "images"
    eval_dir.mkdir(parents=True, exist_ok=True)
    for image_id in image_ids:
        source = images[image_id]
        target = eval_dir / source.name
        try:
            target.symlink_to(source)
        except OSError:
            shutil.copy2(source, target)
    return eval_dir


def parse_metrics(stdout: str) -> Dict[str, float]:
    scores: Dict[str, float] = {}
    for line in stdout.splitlines():
        match = METRIC_PATTERN.match(line.strip())
        if match:
            scores[match.group(1)] = float(match.group(2))
    return scores


def run_eval(eval_script: Path, candidates_json: Path, image_dir: Path, references_json: Path) -> Dict[str, float]:
    command = [
        "python",
        str(eval_script),
        str(candidates_json),
        str(image_dir),
        "--references_json",
        str(references_json),
    ]
    proc = subprocess.run(
        command,
        cwd=str(eval_script.parent),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            "Caption metric evaluation failed for "
            f"{candidates_json} with exit code {proc.returncode}\n{proc.stdout}"
        )
    scores = parse_metrics(proc.stdout)
    missing = [metric for metric in METRICS if metric not in scores]
    if missing:
        raise RuntimeError(
            f"Missing metrics {missing} in BrainHub output for {candidates_json}\n{proc.stdout}"
        )
    return scores


def candidate_path(args: argparse.Namespace, modality: str, condition: str, subject: str) -> Path:
    tag = MODALITY_FILE_TAG[modality]
    filename = args.candidate_pattern.format(tag=tag, modality=modality, subject=subject)
    return args.caption_root / MODALITY_DIR[modality] / condition / filename


def write_outputs(rows: List[Dict[str, object]], output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    fieldnames = ["modality", "condition", "subject", "candidate_json"] + METRICS
    csv_path = output_dir / "caption_metrics.csv"
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    summary: Dict[str, Dict[str, Dict[str, float]]] = {}
    for modality in sorted({str(row["modality"]) for row in rows}):
        summary[modality] = {}
        for condition in sorted({str(row["condition"]) for row in rows if row["modality"] == modality}):
            subset = [row for row in rows if row["modality"] == modality and row["condition"] == condition]
            summary[modality][condition] = {
                metric: sum(float(row[metric]) for row in subset) / len(subset)
                for metric in METRICS
                if all(row.get(metric) not in (None, "") for row in subset)
            }

    json_path = output_dir / "caption_metrics_summary.json"
    with json_path.open("w", encoding="utf-8") as f:
        json.dump({"rows": rows, "summary": summary}, f, indent=2)

    print(f"Wrote per-subject metrics: {csv_path}")
    print(f"Wrote summary metrics: {json_path}")


def validate_keys(
    candidates_json: Path,
    references_json: Path,
    images: Mapping[str, Path],
) -> List[str]:
    candidates = load_json(candidates_json)
    references = load_json(references_json)
    image_ids = sorted(candidates)
    missing_refs = sorted(set(image_ids) - set(references))
    missing_images = sorted(set(image_ids) - set(images))
    if missing_refs:
        raise KeyError(f"{references_json} is missing {len(missing_refs)} references, e.g. {missing_refs[:5]}")
    if missing_images:
        raise FileNotFoundError(f"Image dir is missing {len(missing_images)} images, e.g. {missing_images[:5]}")
    return image_ids


def main() -> None:
    args = parse_args()
    subjects = [normalize_subject(subject) for subject in args.subjects]
    args.eval_script = args.eval_script.resolve()
    if not args.eval_script.exists():
        raise FileNotFoundError(f"BrainHub eval script does not exist: {args.eval_script}")

    rows: List[Dict[str, object]] = []
    image_cache: Dict[Path, Dict[str, Path]] = {}

    for modality in args.modalities:
        references_json = (args.references_json or DEFAULT_REFERENCES[modality]).resolve()
        image_dir = (args.image_dir or DEFAULT_IMAGE_DIRS[modality]).resolve()
        if not references_json.exists():
            raise FileNotFoundError(f"Reference JSON does not exist for {modality}: {references_json}")
        if image_dir not in image_cache:
            image_cache[image_dir] = collect_images(image_dir)

        for condition in args.conditions:
            for subject in subjects:
                candidates_json = candidate_path(args, modality, condition, subject).resolve()
                if not candidates_json.exists():
                    message = f"Missing candidate file: {candidates_json}"
                    if args.skip_missing:
                        print(f"Skipping: {message}")
                        continue
                    raise FileNotFoundError(message)

                image_ids = validate_keys(candidates_json, references_json, image_cache[image_dir])
                print(
                    f"{modality.upper()} {condition} sub-{subject}: "
                    f"{len(image_ids)} captions from {candidates_json}"
                )
                if args.dry_run:
                    continue

                with tempfile.TemporaryDirectory(prefix="brainflora_caption_eval_") as temp:
                    eval_image_dir = make_eval_image_dir(image_cache[image_dir], image_ids, Path(temp))
                    scores = run_eval(args.eval_script, candidates_json, eval_image_dir, references_json)

                row: Dict[str, object] = {
                    "modality": modality,
                    "condition": condition,
                    "subject": f"sub-{subject}",
                    "candidate_json": str(candidates_json),
                }
                row.update(scores)
                rows.append(row)

    if args.dry_run:
        print("Dry run complete.")
        return

    if not rows:
        raise RuntimeError("No caption files were evaluated.")
    write_outputs(rows, args.output_dir)


if __name__ == "__main__":
    main()
